name: Format, Analyze and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # runs the CI weekly
    - cron: "0 0 * * 0"

jobs:
  default_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'
      - run: flutter doctor
      - run: flutter pub get
      - run: dart format --set-exit-if-changed -l 120 lib -l 120 
      - run: flutter analyze lib 
      - run: flutter test --no-pub 
